export const APP_ROUTE_SEGMENTS = {
  admin: "admin",
  dashboard: "dashboard",
  profile: "profile",
  users: "users",
  contentManagement: "content-management",
  insights: "insights",
  incidentTrends: "incident-trends",
  patterns: "patterns",
  createAdmin: "create-admin",
  feedback: "feedback",
  earnings: "earnings",
  subscriptions: "subscriptions",
  settings: "settings",
  changePassword: "change-password",
  privacyPolicy: "privacy-policy",
  termsConditions: "terms-conditions",
  login: "login",
  forgotPassword: "forgot-password",
  verifyOtp: "verify-otp",
  resetPassword: "reset-password",
} as const;

export const APP_ROUTE_PATHS = {
  root: "/",
  adminRoot: `/${APP_ROUTE_SEGMENTS.admin}`,
  adminDashboard: `/${APP_ROUTE_SEGMENTS.admin}/${APP_ROUTE_SEGMENTS.dashboard}`,
  adminProfile: `/${APP_ROUTE_SEGMENTS.admin}/${APP_ROUTE_SEGMENTS.profile}`,
  adminUsers: `/${APP_ROUTE_SEGMENTS.admin}/${APP_ROUTE_SEGMENTS.users}`,
  adminContentManagement: `/${APP_ROUTE_SEGMENTS.admin}/${APP_ROUTE_SEGMENTS.contentManagement}`,
  adminInsights: `/${APP_ROUTE_SEGMENTS.admin}/${APP_ROUTE_SEGMENTS.insights}`,
  adminInsightsIncidentTrends: `/${APP_ROUTE_SEGMENTS.admin}/${APP_ROUTE_SEGMENTS.insights}/${APP_ROUTE_SEGMENTS.incidentTrends}`,
  adminInsightsPatterns: `/${APP_ROUTE_SEGMENTS.admin}/${APP_ROUTE_SEGMENTS.insights}/${APP_ROUTE_SEGMENTS.patterns}`,
  adminCreateAdmin: `/${APP_ROUTE_SEGMENTS.admin}/${APP_ROUTE_SEGMENTS.createAdmin}`,
  adminFeedback: `/${APP_ROUTE_SEGMENTS.admin}/${APP_ROUTE_SEGMENTS.feedback}`,
  adminEarnings: `/${APP_ROUTE_SEGMENTS.admin}/${APP_ROUTE_SEGMENTS.earnings}`,
  adminSubscriptions: `/${APP_ROUTE_SEGMENTS.admin}/${APP_ROUTE_SEGMENTS.subscriptions}`,
  adminSettings: `/${APP_ROUTE_SEGMENTS.admin}/${APP_ROUTE_SEGMENTS.settings}`,
  adminChangePassword: `/${APP_ROUTE_SEGMENTS.admin}/${APP_ROUTE_SEGMENTS.settings}/${APP_ROUTE_SEGMENTS.changePassword}`,
  adminPrivacyPolicy: `/${APP_ROUTE_SEGMENTS.admin}/${APP_ROUTE_SEGMENTS.settings}/${APP_ROUTE_SEGMENTS.privacyPolicy}`,
  adminTermsConditions: `/${APP_ROUTE_SEGMENTS.admin}/${APP_ROUTE_SEGMENTS.settings}/${APP_ROUTE_SEGMENTS.termsConditions}`,
  login: `/${APP_ROUTE_SEGMENTS.login}`,
  forgotPassword: `/${APP_ROUTE_SEGMENTS.forgotPassword}`,
  verifyOtp: `/${APP_ROUTE_SEGMENTS.verifyOtp}`,
  resetPassword: `/${APP_ROUTE_SEGMENTS.resetPassword}`,
} as const;
